# Generated by Django 6.0.7 on 2026-08-28 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_allocator", "0002_uploadedfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_type", models.CharField(max_length=30)),
                ("branch_code", models.CharField(blank=True, max_length=20)),
                ("slot", models.CharField(blank=True, max_length=20)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="exam_allocator.exam",
                    ),
                ),
            ],
        ),
    ]
