# Generated by Django 6.0.7 on 2026-08-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_allocator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('upload_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_kind', models.CharField(choices=[('STUDENT', 'Student List'), ('CLASSROOM', 'Classroom List'), ('TIMETABLE', 'Exam Timetable')], max_length=20)),
                ('source_format', models.CharField(choices=[('PDF', 'PDF'), ('XLSX', 'Excel'), ('IMAGE', 'Image')], max_length=10)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('VALIDATED', 'Validated'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True)),
            ],
        ),
    ]
