# Generated by Django 6.0.7 on 2026-08-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_allocator", "0003_examtarget"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllocationSession",
            fields=[
                ("session_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PROCESSING", "Processing"),
                            ("READY", "Ready"),
                            ("ALLOCATING", "Allocating"),
                            ("COMPLETED", "Completed"),
                            ("ARCHIVED", "Archived"),
                            ("FAILED", "Failed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
