# Generated by Django 6.0.7 on 2026-08-29 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_allocator", "0004_allocationsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="exam_allocator.allocationsession",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="exam_allocator.allocationsession",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="exam_allocator.allocationsession",
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_files",
                to="exam_allocator.allocationsession",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="department_code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="subject",
            name="subject_code",
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                fields=("session", "department_code"),
                name="unique_department_per_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                fields=("session", "room_number"), name="unique_room_per_session"
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("session", "subject_code"), name="unique_subject_per_session"
            ),
        ),
    ]
