# Generated by Django 5.2.17 on 2026-09-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_allocator', '0005_department_session_room_session_subject_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtarget',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
