# Generated by Django 5.2.17 on 2026-09-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_allocator', '0006_alter_examtarget_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examtarget',
            name='id',
        ),
        migrations.AddField(
            model_name='examtarget',
            name='target_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
