# Generated by Django 5.2.17 on 2026-10-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_allocator', '0007_remove_examtarget_id_examtarget_target_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='uni_reg_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
