# Generated by Django 5.2.17 on 2026-10-03 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_allocator', '0008_student_admission_no_student_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_kind',
            field=models.CharField(choices=[('STUDENT', 'Student List'), ('CLASSROOM', 'Classroom List'), ('TIMETABLE', 'Exam Timetable'), ('ELECTIVE', 'Elective List')], max_length=20),
        ),
        migrations.CreateModel(
            name='ElectiveGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_code', models.CharField(max_length=20)),
                ('department_name', models.CharField(blank=True, max_length=100)),
                ('elective_label', models.CharField(max_length=100)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elective_groups', to='exam_allocator.allocationsession')),
            ],
        ),
        migrations.CreateModel(
            name='ElectiveSubject',
            fields=[
                ('elective_subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_code', models.CharField(max_length=30)),
                ('subject_name', models.CharField(max_length=150)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='exam_allocator.electivegroup')),
            ],
        ),
        migrations.CreateModel(
            name='ElectiveStudentRegistration',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('roll_number', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=150)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elective_registrations', to='exam_allocator.student')),
                ('elective_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_registrations', to='exam_allocator.electivesubject')),
            ],
        ),
        migrations.AddConstraint(
            model_name='electivegroup',
            constraint=models.UniqueConstraint(fields=('session', 'department_code', 'elective_label'), name='unique_elective_group_per_session'),
        ),
        migrations.AddConstraint(
            model_name='electivesubject',
            constraint=models.UniqueConstraint(fields=('group', 'subject_code'), name='unique_elective_subject_per_group'),
        ),
        migrations.AddConstraint(
            model_name='electivestudentregistration',
            constraint=models.UniqueConstraint(fields=('elective_subject', 'roll_number'), name='unique_student_per_elective_subject'),
        ),
    ]
