# Generated by Django 5.2.17 on 2026-10-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_allocator', '0009_alter_uploadedfile_file_kind_electivegroup_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='electivegroup',
            name='unique_elective_group_per_session',
        ),
        migrations.AddField(
            model_name='electivestudentregistration',
            name='class_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='electivestudentregistration',
            name='department',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='electivestudentregistration',
            name='is_unresolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electivestudentregistration',
            name='source_row',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electivestudentregistration',
            name='source_sheet_or_page',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='electivestudentregistration',
            name='unresolved_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='electivesubject',
            name='elective_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='electivesubject',
            name='original_subject_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='electivegroup',
            name='department_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='electivegroup',
            name='department_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='electivestudentregistration',
            name='source_file',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='electivesubject',
            name='subject_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='electivesubject',
            name='subject_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='electivegroup',
            constraint=models.UniqueConstraint(fields=('session', 'elective_label'), name='unique_elective_group_per_session'),
        ),
    ]
