# Generated by Django 5.2.17 on 2026-10-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_allocator', '0010_remove_electivegroup_unique_elective_group_per_session_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='unique_roll_number_per_class',
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('roll_number', ''), _negated=True), fields=('student_class', 'roll_number'), name='unique_roll_number_per_class'),
        ),
    ]
